site_name: Fink
repo_url: https://github.com/astrolabsoftware/fink-broker
edit_uri: ""

nav:
    - Home: index.md
    - User Guide:
      - Welcome: user_guide/infrastructure.md
      - Configuration: user_guide/configuration.md
      - Databases: user_guide/database.md
      - Services: user_guide/available-services.md
      - Dashboard: user_guide/dashboard.md
      - Simulating streams: user_guide/simulator.md
      - Testing Fink: user_guide/testing-fink.md
      - Redistributing alerts: user_guide/streaming-out.md
      - Howto: user_guide/howto.md
    - About:
      - Release Notes: release-notes.md
      - Contributing: contributing.md
      - License: license.md

# theme: readthedocs

copyright: Copyright &copy; 2018-19 <a href="https://astrolabsoftware.github.io/">AstroLab Software</a>.
