site_name: Fink
repo_url: https://github.com/astrolabsoftware/fink-broker

nav:
    - Home: index.md
    - User Guide:
      - Infrastructure: user_guide/infrastructure.md
      - Configuration: user_guide/configuration.md
      - Deploying a service: user_guide/deploying-your-docs.md
      - Simulating streams: user_guide/simulator.md
      - Testing Fink: user_guide/testing-the-broker.md
      - Adding a new service: user_guide/writing-your-docs.md
      - webUI: user_guide/webui.md
    - About:
      - Release Notes: release-notes.md
      - Contributing: contributing.md
      - License: license.md

# theme: readthedocs

copyright: Copyright &copy; 2018-19 <a href="https://astrolabsoftware.github.io/">AstroLab Software</a>.
