name: "e2e: platform=sentinel, survey=rubin, science=true, infra=github"

on:
  push:
  pull_request:
    branches:
      - master
  schedule:
    # At 03:00 UTC on Sunday
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  call-sentinel-template:
    uses: ./.github/workflows/sentinel-template.yml
    with:
      survey: rubin